server:
  port: 8001
spring:
  application:
    name: ishopping-plat-service-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true